### ISSUE TITLE
Magento 2.2.2 CHECKOUT translation

### ISSUE THREAD

**Issue by SoCix** [Imaginaerum/magento2-language-fr-fr#1138]
Hello, 

I am using Magento 2.2.2 translation works fine except for CHECKOUT, do you have any solution pls

how and where to add custom translations in local files

I tried to edit

vendor/imaginaerum/magento2-language-fr-fr but not working

thank You.

**Comment by Imaginaerum** [comment]
Magento 2.1.2,2.2.2,2.2.3 in progress...

**Comment by Imaginaerum** [comment]
Please note: **"Item in Cart"** is not availbale. The fix will be available with the upcoming Magento 2.2.4 release. [https://github.com/magento/magento2/issues/12081#issuecomment-364596374](https://github.com/magento/magento2/issues/12081#issuecomment-364596374)

**Comment by dzSo** [comment]
@Imaginaerum Great thank You.

**Comment by marco7319** [comment]
version 223 "Item in Cart" non traduit

**Comment by wget** [comment]
@marco7319 Merci mais ce pack de langue n'est pas encore compatible avec la version 2.2 de Magento. Ma société est dessus, mais ça prend un peu de temps :)

**Comment by SoCix** [comment]
Hello, thank you again,

I tried to make some changes on some lines in

> /vendor/imaginaerum/magento2-language-fr-fr/dictionary.csv

Changes for single words work fine, but compound words do not work (even with ""), is there any explanation please, or should I do something after editing the files like recompile or something like that

exemple: 
"Your product","Votre produit"
"View cart","Voir le panier"

in order to create a new translations should do the same thing (edit the same file dictionary.csv)

Thank You @Imaginaerum

**Comment by wget** [comment]
@SoCix Yes, it depends on the Magento mode you are: standard, developer or production. I would strongly advise you to use developer mode you you are debugging.

Don't forget to clean:
```
rm -r var/cache/* var/di/* var/generation/* var/page_cache/* var/composer_home/* var/view_preprocessed/* pub/static/*
php bin/magento setup:di:compile
php ./bin/magento setup:static-content:deploy en_US
php ./bin/magento setup:static-content:deploy fr_FR
```

You need to run the aforementioned commands one after another on their own dedicated line. I mean Magento is still suffering on old bug and CLI commands cannot be run using `&&`. This sounds stupid but I had an equivalent issue a few times ago with French (and other translations) not being regenerated. The same applies especially with `setup:static-content:deploy`, the languages cannot be on the same line passed as argument, you have to write the same command for each language you want to generate. Please note English is needed as well because it is used as fallback when French translation is not available. Not generating it was causing me a few issues in the past. Don't know if this still applies with 2.2. and 2.3.
