### ISSUE TITLE
Release the last changes?

### ISSUE THREAD

**Issue by VincentMarmiesse** [Imaginaerum/magento2-language-fr-fr#1156]
Hello,
Do you plan to release the last changes? Because they are not available through Packagist :(

**Comment by wget** [comment]
Hi @VincentMarmiesse.

Actually this package is going to be deprecated. Magento since they have been bought by Adobe began to make some substantial changes in their own infrastructure.

First, they have now officially started organizing official translations: https://crowdin.com/project/magento-2

This means I'll have to upload all the strings we have here (which are in a much better shape) to their crowdin instance.

I'm currently discussing with Magento admins in order to have API write access. Obviously I won't import strings by hand.

The only thing that is missing from their interface is the ability to make a daily package update and publish it to Packagist.

In order to fix this issue, I decided to build open source CI scripts. These will be published to the open project [Frento](https://github.com/frento). Creating an organization was quite needed since this would allow us to have several admins on the project and if someone leaves, we are not dependent on a specific account.

To answer your specific question, I don't have write access to the Imaginaerum package on packagist so I cannot publish an update myself. This is why having an organization is best :)
