### ISSUE TITLE
Installer manuellement , At checkout page is still Inglés

### ISSUE THREAD

**Issue by zhiyicai** [Imaginaerum/magento2-language-fr-fr#475]
Installer manuellement
At checkout page is still Inglés

![20160415171523](https://cloud.githubusercontent.com/assets/13891311/14565943/bdfdc322-032d-11e6-907a-ee7ad60d8e7a.png)

**Comment by Imaginaerum** [comment]
Thanks for your reply. I test it.

**Comment by zhiyicai** [comment]
If you have already solve this problem, please , theach me how yo solve it ! Thanks

**Comment by Imaginaerum** [comment]
First, try to disable your cache and  **flush** cache (not clean, but flush...).
The best method to install this pack is composer. See: http://imaginaerum.github.io/magento2-language-fr-fr/en.html (installation section).

**Comment by zhiyicai** [comment]
I have already disable cache and flush cache, but it does not work.

**Comment by Imaginaerum** [comment]
I will test on a Magento instance.

**Comment by zhiyicai** [comment]
Ok, thank you very much :smile:

**Comment by Imaginaerum** [comment]
French language pack v100.6.0 is ready, try it ;) - I test on a magento instance

**Comment by Imaginaerum** [comment]
It's work for me.

![testm2](https://cloud.githubusercontent.com/assets/7314174/14580003/921c72d4-03bf-11e6-8308-f6c28a8642fe.png)

**Comment by Imaginaerum** [comment]
I close issue. But i can help you to sole it.

**Comment by zhiyicai** [comment]
is it Installer manuellement or Installer via Composer ?

**Comment by Imaginaerum** [comment]
As you want. But use composer.

**Comment by zhiyicai** [comment]
i Installer manuellement, but,At checkout page is still Inglés.

**Comment by zhiyicai** [comment]
Cloud you try to installer manuellment, check it at checkout page is still Inglés?

**Comment by Imaginaerum** [comment]
It's work for me (composer and manual install)

**Comment by zhiyicai** [comment]
I unzip it into /magento/app/i18n/imaginaerum/fr_fr folder.  is correct ?

![20160416112010](https://cloud.githubusercontent.com/assets/13891311/14580189/8e2cf648-03c5-11e6-995b-d9d9e791c5c8.png)

**Comment by Imaginaerum** [comment]
It's correct. What is your Magento version ? Use 2.0.4

**Comment by zhiyicai** [comment]
My version is Magento 2.0.4 , i have tried verion Mangeto 2.0.0 | 2.0.2 | 2.0.4 .is not working.

**Comment by Imaginaerum** [comment]
I think it' a cache issue. Some user have the same problem. After deep clean, it's work. 

To purge out-of-date items from the cache, you can clean or flush cache types:

Cleaning a cache type deletes all items from enabled Magento cache types only. In other words, this option does not affect other processes or applications because it cleans only the cache that Magento uses.

Disabled cache types are not cleaned.

Flushing a cache type purges the cache storage, which might affect other processes applications that are using the same storage.

Flush cache types if you’ve already tried cleaning the cache and you’re still having issues that you cannot isolate.

You can also clean and flush cache types in the Magento Admin. Go to System > Tools > Cache Management. Flush Cache Storage is equivalent to magento cache:flush. Flush Magento Cache is equivalent to magento cache:clean.
